#!/bin/bash
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_100_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_101_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_102_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_103_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_104_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_105_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_106_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_107_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_108_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_109_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_10_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_110_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_111_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_112_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_113_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_114_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_115_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_116_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_117_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_118_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_119_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_11_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_120_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_12_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_13_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_14_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_15_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_16_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_17_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_18_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_19_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_1_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_20_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_21_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_22_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_23_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_24_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_25_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_26_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_27_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_28_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_29_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_2_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_30_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_31_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_32_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_33_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_34_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_35_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_36_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_37_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_38_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_39_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_3_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_40_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_41_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_42_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_43_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_44_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_45_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_46_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_47_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_48_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_49_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_4_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_50_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_51_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_52_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_53_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_54_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_55_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_56_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_57_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_58_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_59_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_5_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_60_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_61_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_62_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_63_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_64_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_65_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_66_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_67_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_68_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_69_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_6_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_70_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_71_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_72_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_73_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_74_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_75_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_76_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_77_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_78_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_79_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_7_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_80_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_81_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_82_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_83_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_84_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_85_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_86_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_87_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_88_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_89_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_8_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_90_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_91_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_92_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_93_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_94_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_95_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_96_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_97_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_98_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_99_f
./programs/parse_structure_output/parse_structure_output -f sw_results/structure/popgen/admixture/Results/admixture_run_9_f
