#!/bin/bash
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLAB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_ALST-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-FLCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLAB-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLCC-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLFD-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLFD-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLFD-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLFD-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLFD-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLHB-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLHB-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLHB-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLHB-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-ALST.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLAB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLPB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLKB-TXSP.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-ALST.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLAB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLPB-TXSP.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLSG-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLSG-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLSG-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLSI-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_FLSI-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXCB-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-ALST.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLAB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLFD.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLHB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLSG.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-FLSI.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-TXCB.tsv -o ~/Documents/Sarahs/Popgen/stacks/
./stacks_genomeCIs -i ~/Documents/Sarahs/Popgen/stacks/batch_1.fst_TXSP-TXCC.tsv -o ~/Documents/Sarahs/Popgen/stacks/
