#!/bin/bash
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_10_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_11_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_12_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_13_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_14_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_15_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_16_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_17_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_18_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_19_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_1_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_20_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_21_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_22_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_23_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_24_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_25_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_26_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_27_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_28_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_29_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_2_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_30_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_31_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_32_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_33_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_34_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_35_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_36_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_37_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_38_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_39_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_3_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_40_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_41_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_42_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_43_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_44_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_45_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_46_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_47_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_48_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_49_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_4_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_50_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_51_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_52_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_53_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_54_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_55_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_56_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_57_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_58_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_59_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_5_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_60_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_6_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_7_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_8_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_str/admix/Results/admix_run_9_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_10_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_11_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_12_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_13_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_14_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_15_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_16_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_17_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_18_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_19_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_1_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_20_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_21_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_22_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_23_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_24_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_25_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_26_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_27_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_28_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_29_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_2_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_30_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_31_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_32_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_33_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_34_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_35_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_36_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_37_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_38_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_39_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_3_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_40_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_41_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_42_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_43_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_44_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_45_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_46_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_47_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_48_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_49_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_4_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_50_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_51_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_52_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_53_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_54_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_55_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_56_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_57_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_58_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_59_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_5_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_60_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_61_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_62_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_63_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_64_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_65_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_66_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_67_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_68_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_69_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_6_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_7_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_8_f
./programs/parse_structure_output/parse_structure_output -f nerophis/structure/nop_popgen/no_admix/Results/no_admix_run_9_f
