sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABNP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLABP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCDB1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCDB2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCDB6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCDB7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCNP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLCCP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLFDP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBDB8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBNP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBNP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLHBP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGDB1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGDB2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGDB3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSGP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP7_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_FLSIP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBNP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP18_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCBP9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF17_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF19_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF20_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF21_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF22_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF23_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF24_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCF9_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCJB_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCJC_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCJD_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCJE_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCJF_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCNP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCNP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP10_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP11_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP12_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP13_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP14_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP15_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP16_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP1_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP2_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP3_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP4_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP5_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP6_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP8_align -o ./corstacks
sstacks -b 1 -c ./corstacks/batch_1 -s ./corstacks/sample_TXCCP9_align -o ./corstacks
