#!/bin/bash
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_100_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_101_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_102_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_103_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_104_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_105_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_106_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_107_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_108_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_109_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_10_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_110_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_111_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_112_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_113_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_114_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_115_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_116_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_117_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_118_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_119_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_11_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_120_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_121_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_122_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_123_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_124_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_125_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_126_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_127_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_128_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_129_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_12_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_130_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_131_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_132_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_133_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_134_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_135_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_136_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_137_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_138_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_139_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_13_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_140_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_141_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_142_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_143_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_144_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_145_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_146_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_147_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_148_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_149_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_14_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_150_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_151_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_152_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_153_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_154_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_155_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_156_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_15_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_16_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_17_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_18_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_19_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_1_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_20_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_21_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_22_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_23_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_24_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_25_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_26_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_27_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_28_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_29_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_2_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_30_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_31_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_32_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_33_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_34_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_35_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_36_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_37_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_38_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_39_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_3_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_40_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_41_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_42_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_43_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_44_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_45_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_46_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_47_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_48_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_49_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_4_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_50_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_51_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_52_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_53_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_54_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_55_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_56_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_57_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_58_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_59_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_5_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_60_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_61_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_62_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_63_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_64_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_65_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_66_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_67_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_68_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_69_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_6_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_70_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_71_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_72_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_73_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_74_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_75_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_76_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_77_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_78_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_79_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_7_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_80_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_81_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_82_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_83_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_84_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_85_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_86_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_87_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_88_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_89_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_8_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_90_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_91_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_92_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_93_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_94_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_95_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_96_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_97_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_98_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_99_f
./programs/parse_structure_output/parse_structure_output -f fwsw_results/structure/fwsw/admix/Results/admix_run_9_f
