pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AAACGG.fq_2013-24-10_SscoAlign.sam -i 1
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AACGTT.fq_2013-24-10_SscoAlign.sam -i 2
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AACTGA.fq_2013-24-10_SscoAlign.sam -i 3
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AAGACG.fq_2013-24-10_SscoAlign.sam -i 4
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AAGCTA.fq_2013-24-10_SscoAlign.sam -i 5
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AATATC.fq_2013-24-10_SscoAlign.sam -i 6
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AATGAG.fq_2013-24-10_SscoAlign.sam -i 7
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACAAGA.fq_2013-24-10_SscoAlign.sam -i 8
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACAGCG.fq_2013-24-10_SscoAlign.sam -i 9
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACATAC.fq_2013-24-10_SscoAlign.sam -i 10
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACCATG.fq_2013-24-10_SscoAlign.sam -i 11
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACCCCC.fq_2013-24-10_SscoAlign.sam -i 12
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACTCTT.fq_2013-24-10_SscoAlign.sam -i 13
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ACTGGC.fq_2013-24-10_SscoAlign.sam -i 14
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGCCAT.fq_2013-24-10_SscoAlign.sam -i 15
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGCGCA.fq_2013-24-10_SscoAlign.sam -i 16
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGGGTC.fq_2013-24-10_SscoAlign.sam -i 17
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGGTGT.fq_2013-24-10_SscoAlign.sam -i 18
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGTAGG.fq_2013-24-10_SscoAlign.sam -i 19
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_AGTTAA.fq_2013-24-10_SscoAlign.sam -i 20
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ATAGTA.fq_2013-24-10_SscoAlign.sam -i 21
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ATCAAA.fq_2013-24-10_SscoAlign.sam -i 22
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ATGCAC.fq_2013-24-10_SscoAlign.sam -i 23
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ATGTTG.fq_2013-24-10_SscoAlign.sam -i 24
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_ATTCCG.fq_2013-24-10_SscoAlign.sam -i 25
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CAAAAA.fq_2013-24-10_SscoAlign.sam -i 26
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CAATCG.fq_2013-24-10_SscoAlign.sam -i 27
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CACCTC.fq_2013-24-10_SscoAlign.sam -i 28
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CAGGCA.fq_2013-24-10_SscoAlign.sam -i 29
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CATACT.fq_2013-24-10_SscoAlign.sam -i 30
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCATTT.fq_2013-24-10_SscoAlign.sam -i 31
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCCGGT.fq_2013-24-10_SscoAlign.sam -i 32
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCCTAA.fq_2013-24-10_SscoAlign.sam -i 33
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCGAGG.fq_2013-24-10_SscoAlign.sam -i 34
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCGCAT.fq_2013-24-10_SscoAlign.sam -i 35
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CCTAAC.fq_2013-24-10_SscoAlign.sam -i 36
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGAGGC.fq_2013-24-10_SscoAlign.sam -i 37
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGCAGA.fq_2013-24-10_SscoAlign.sam -i 38
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGCGTG.fq_2013-24-10_SscoAlign.sam -i 39
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGGTCC.fq_2013-24-10_SscoAlign.sam -i 40
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGTCTA.fq_2013-24-10_SscoAlign.sam -i 41
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CGTGAT.fq_2013-24-10_SscoAlign.sam -i 42
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTACAG.fq_2013-24-10_SscoAlign.sam -i 43
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTCGCC.fq_2013-24-10_SscoAlign.sam -i 44
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTGCGA.fq_2013-24-10_SscoAlign.sam -i 45
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTGGTT.fq_2013-24-10_SscoAlign.sam -i 46
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTTATG.fq_2013-24-10_SscoAlign.sam -i 47
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_CTTTGC.fq_2013-24-10_SscoAlign.sam -i 48
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TCTTCT.fq_2013-24-10_SscoAlign.sam -i 49
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TGAACC.fq_2013-24-10_SscoAlign.sam -i 50
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TGACAA.fq_2013-24-10_SscoAlign.sam -i 51
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TGCCCG.fq_2013-24-10_SscoAlign.sam -i 52
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TGCTTA.fq_2013-24-10_SscoAlign.sam -i 53
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TGGGGA.fq_2013-24-10_SscoAlign.sam -i 54
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTATGA.fq_2013-24-10_SscoAlign.sam -i 55
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTCCGT.fq_2013-24-10_SscoAlign.sam -i 56
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTCTAG.fq_2013-24-10_SscoAlign.sam -i 57
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTGAGC.fq_2013-24-10_SscoAlign.sam -i 58
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTTAAT.fq_2013-24-10_SscoAlign.sam -i 59
pstacks -m 10 -p 6 -o /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/ -t sam -f /home/joneslab/Documents/Sarahs/PstI_Data/alignments/sample_TTTGTC.fq_2013-24-10_SscoAlign.sam -i 60
