files="sample_FLFDP1_align
sample_FLFDP24_align
sample_FLFDP15_align
sample_FLFDP9_align
sample_FLFDP18_align
sample_FLFDF10_align
sample_FLFDF2_align
sample_FLFDP2_align
sample_FLFDP17_align
sample_FLFDP3_align
sample_FLFDP19_align
sample_FLFDP20_align
sample_FLFDF9_align
sample_FLFDP11_align
sample_FLFDF16_align
sample_FLFDP21_align
sample_FLFDF11_align
sample_FLFDP5_align
sample_FLFDF1_align
sample_FLFDF15_align
sample_FLFDP13_align
sample_FLFDP6_align
sample_FLFDP23_align
sample_FLFDF23_align
sample_FLFDP4_align
sample_FLFDF8_align
sample_FLFDP22_align
sample_FLFDF7_align
sample_FLFDF4_align
sample_FLFDP12_align
sample_FLFDP7_align
sample_FLFDF18_align
sample_FLFDP16_align
sample_FLFDF6_align
sample_FLFDF17_align
sample_FLFDF5_align
sample_FLFDF20_align
sample_FLFDF14_align
sample_FLFDP8_align
sample_FLFDF13_align
sample_FLCCF20_align
sample_FLCCF18_align
sample_FLCCF21_align
sample_FLCCF22_align
sample_FLCCDB2_align
sample_FLCCF16_align
sample_FLCCF4_align
sample_FLCCF13_align
sample_FLCCF14_align
sample_FLCCP4_align
sample_FLCCDB6_align
sample_FLCCNP11_align
sample_FLCCDB7_align
sample_FLCCP2_align
sample_FLCCNP6_align
sample_FLCCDB1_align
sample_FLCCNP5_align
sample_FLCCP5_align
sample_FLCCF11_align
sample_FLCCNP2_align
sample_FLCCNP4_align
sample_FLCCF3_align
sample_FLCCP3_align
sample_FLCCF19_align
sample_FLCCP6_align
sample_FLCCNP8_align
sample_FLCCP7_align
sample_FLCCNP14_align
sample_FLCCNP12_align
sample_FLCCF17_align
sample_FLCCP1_align
sample_FLCCNP1_align
sample_FLCCF1_align
sample_FLCCNP3_align
sample_FLCCF9_align"

for file in $files
do
	echo $file
	samtools view -bS /home/joneslab/Documents/Sarahs/Popgen/samples/${file}.sam | \
		samtools sort - ${file}_sorted	
done

echo "running mpileup"
samtools mpileup -g -f allpaths_cms1.scaff_fixed.fa -b test_samples.txt > fixed_test_all.bcf
samtools mpileup -u -f allpaths_cms1.scaff_fixed.fa -b test_samples.txt | bcftools call -mv -Ov > pipe.test2.vcf



