#!/bin/bash
files="sample_AAACGG
sample_AACGTT
sample_AACTGA
sample_AAGACG
sample_AAGCTA
sample_AATATC
sample_AATGAG
sample_ACAAGA
sample_ACAGCG
sample_ACATAC
sample_ACCATG
sample_ACCCCC
sample_ACTCTT
sample_ACTGGC
sample_AGCCAT
sample_AGCGCA
sample_AGGGTC
sample_AGGTGT
sample_AGTAGG
sample_AGTTAA
sample_ATAGTA
sample_ATCAAA
sample_ATGCAC
sample_ATGTTG
sample_ATTCCG
sample_CAAAAA
sample_CAATCG
sample_CACCTC
sample_CAGGCA
sample_CATACT
sample_CCATTT
sample_CCCGGT
sample_CCCTAA
sample_CCGAGG
sample_CCGCAT
sample_CCTAAC
sample_CGAGGC
sample_CGCAGA
sample_CGCGTG
sample_CGGTCC
sample_CGTCTA
sample_CGTGAT
sample_CTACAG
sample_CTCGCC
sample_CTGCGA
sample_CTGGTT
sample_CTTATG
sample_CTTTGC
sample_TCTTCT
sample_TGAACC
sample_TGACAA
sample_TGCCCG
sample_TGCTTA
sample_TGGGGA
sample_TTATGA
sample_TTCCGT
sample_TTCTAG
sample_TTGAGC
sample_TTTAAT
sample_TTTGTC"

for file in $files
do
	samtools view -b -S -o ./new_pipeline/${file}.bam \
	 ./alignments/${file}.fq_2013-24-10_SscoAlign.sam
	samtools sort ./new_pipeline/${file}.bam ./new_pipeline/${file}.sorted 
	samtools index ./new_pipeline/${file}.sorted.bam
done
