sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AAACGG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AACGTT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AACTGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AAGACG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AAGCTA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AATATC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AATGAG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACAAGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACAGCG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACATAC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACCATG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACCCCC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACTCTT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ACTGGC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGCCAT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGCGCA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGGGTC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGGTGT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGTAGG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_AGTTAA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ATAGTA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ATCAAA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ATGCAC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ATGTTG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_ATTCCG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CAAAAA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CAATCG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CACCTC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CAGGCA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CATACT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCATTT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCCGGT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCCTAA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCGAGG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCGCAT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CCTAAC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGAGGC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGCAGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGCGTG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGGTCC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGTCTA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CGTGAT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTACAG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTCGCC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTGCGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTGGTT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTTATG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_CTTTGC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TCTTCT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TGAACC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TGACAA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TGCCCG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TGCTTA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TGGGGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTATGA.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTCCGT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTCTAG.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTGAGC.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTTAAT.fq_2013-24-10_SscoAlign -o ./rxstacks
sstacks -b 2 -c /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/batch_2 -p 6 -s /home/joneslab/Documents/Sarahs/PstI_Data/rxstacks/sample_TTTGTC.fq_2013-24-10_SscoAlign -o ./rxstacks
