sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AAACGG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AACTGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AAGACG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AAGCTA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AATATC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AATGAG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACAAGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACAGCG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACATAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACCATG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACCCCC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ACTCTT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AGCCAT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AGCGCA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AGGTGT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AGTAGG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_AGTTAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ATAGTA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ATGCAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ATGTTG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_ATTCCG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CAAAAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CAATCG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CATACT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CCATTT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CCCTAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CCGAGG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CCGCAT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CCTAAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGAGGC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGCAGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGCGTG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGGTCC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGTCTA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CGTGAT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTACAG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTCGCC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTGCGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTGGTT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTTATG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_CTTTGC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GAAATG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GAACCA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GACGAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GACTCT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GAGAGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GATCGT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GCAGAT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GCATGG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GCCGTA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GCGCTG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GCTCAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GGACTT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GGGCGC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GGGGCG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GGTACA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GGTTTG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTAAGT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTATCC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTCATC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTGCCT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTGTAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_GTTGGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TAAGCT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TAATTC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TACGGG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TAGTAT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TATCAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCAAAG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCCTGC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCGATT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCGCCA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCGGAC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TCTTCT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TGAACC.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TGACAA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TGCCCG.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TGCTTA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TGGGGA.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TTCCGT.fq_align -o ./cor_stacks
sstacks -b 1 -c ./cor_stacks/batch_1 -s ./cor_stacks/sample_TTTAAT.fq_align
